# Default values for csm-application-mobility.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent

controller:
  image: dellemc/csm-application-mobility-controller:v0.2.0

# csm-application-mobility requires cert-manager. If cert-manager is not already present in cluster, set enabled to true to install it too.
cert-manager:
  enabled: false

# csm-application-mobility requires velero. If velero is already installed on the cluster, specify the namespace in which velero is deployed. Default value is "velero"
veleroNamespace: velero

# name of the license Secret used by csm-application-mobility.
licenseName: license

# csm-application-mobility requires velero. If velero is already installed on the cluster, specify the name of the secret in velero namespace that has credentials to access object store.
# Default value is "cloud-credentials".
objectstore:
  secretName:

# csm-application-mobility requires velero. If velero is not already present in cluster, set enabled to true to install it too.
velero:
  enabled: true
  use-volume-snapshots: false
  deployRestic: true
  cleanUpCRDs: true
  restic:
    # Set to true if installing on OpenShift
    privileged: false

  credentials:
#    Optionally, specify the name of the pre-created secret in the release namespace that holds the object store credentials. Either this or secretContents should be specified.
#    existingSecret: cloud-credentials
#   Optionally, specify the name to be used for secret that will be created to hold object store credentials. Used in conjunction with secretContents.
    name: cloud-creds
#    Optionally, specify the object store access credentials to be stored in a secret with key "cloud". Either this or existingSecret should be provided.
    secretContents:
      cloud: |
        [default]
        aws_access_key_id=access_key
        aws_secret_access_key=secret_access_key

# Based on the objectstore being used , the velero plugin and its configuration may need to change! Below is the sample configuration for using aws object store.
# GCP and Azure plugins configuration are different. See more details at: https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/README.md
  configuration:
    provider: aws
    backupStorageLocation:
      name: default
      bucket: velero-bucket
      config: {}
      #  region:
      #  s3ForcePathStyle:
      #  s3Url:
      #  kmsKeyId:
      #  resourceGroup:
      #  The ID of the subscription containing the storage account, if different from the clusterâ€™s subscription. (Azure only)
      #  subscriptionId:
      #  storageAccount:
      #  publicUrl:
      #  Name of the GCP service account to use for this backup storage location. Specify the
      #  service account here if you want to use workload identity instead of providing the key file.(GCP only)
      #  serviceAccount:

  initContainers:
  - name: dell-custom-velero-plugin
    image: dellemc/csm-application-mobility-velero-plugin:v0.2.0
    volumeMounts:
    - mountPath: /target
      name: plugins
  # - name: velero-plugin-for-aws
  #  image: velero/velero-plugin-for-aws:v1.5.0
  #  volumeMounts:
  #  - mountPath: /target
  #    name: plugins
  
# Optionally, uncomment and specify the name of the pre-created namespace to install the module in it
# namespace: 