apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-params
  namespace: {{ .Release.Namespace }}
data:
  driver-config-params.yaml: |
    COSI_LOG_LEVEL: "{{ .Values.logLevel }}"
    COSI_LOG_FORMAT: "{{ .Values.logFormat }}"
