apiVersion: v2
appVersion: "1.0.0"
name: karavi-observability
description: CSM for Observability is part of the [Container Storage Modules](https://github.com/dell/csm) open source suite of Kubernetes storage enablers for Dell EMC storage products. CSm for Observability provides Kubernetes administrators with visibility into metrics and topology data related to containerized storage.
type: application
version: 1.0.0
dependencies:
- name: cert-manager
  version: 1.1.0
  repository: https://charts.jetstack.io
