apiVersion: v2
appVersion: "0.3.1"
name: karavi-observability
description: Karavi Observability is part of the [Karavi](https://github.com/dell/karavi) open source suite of Kubernetes storage enablers for Dell EMC storage products. Karavi Observability provides Kubernetes administrators with visibility into metrics and topology data related to containerized storage.
type: application
version: 0.3.1
dependencies:
- name: cert-manager
  version: 1.1.0
  repository: https://charts.jetstack.io
