apiVersion: v1
appVersion: "1.0"
description: The open-source solution that provides Kubernetes administrators insight into storage usage and performance for containerized applications using Dell products.
name: karavi-powerflex-metrics
version: 0.2.1
