image: <docker-registry>:<port>/karavi-topology:latest
# comma seperated list of provisioner names (ex: csi-vxflexos.dellemc.com)
provisioner_names: csi-vxflexos.dellemc.com
service:
  type: ClusterIP
# location of the signed certificate file
certificateFile:
# location of the private key file
privateKeyFile:
