#
#
# Copyright Â© 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
## K8S/DRIVER ATTRIBUTES
###################################

## CSI PowerStore 
########################
csi-powerstore:
  enabled: false
  namespace: 
  version: "v2.6.0"
  images:
    driverRepository: dellemc
  ## Controller ATTRIBUTES
  controller:
    controllerCount: 2
    healthMonitor:
      enabled: false
    nodeSelector:
    replication:
      enabled: false
      image: dellemc/dell-csi-replicator:v1.4.0
    vgsnapshot:
      enabled: false
      image: dellemc/csi-volumegroup-snapshotter:v1.2.0
    snapshot:
      enabled: true
    resizer:
      enabled: true
  ## Node ATTRIBUTES
  node:
    healthMonitor:
      enabled: false
    nodeSelector:
      # Uncomment if CSM for Resiliency and CSI Driver pods monitor are enabled
    # tolerations:
    # - key: "offline.vxflexos.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # - key: "vxflexos.podmon.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # - key: "offline.unity.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # - key: "unity.podmon.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # - key: "offline.isilon.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # - key: "isilon.podmon.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # - key: "offline.powerstore.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # - key: "powerstore.podmon.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
  storageCapacity:
    enabled: true  
  # Enable this feature only after contact support for additional information
  podmon:
    enabled: false
    image: dellemc/podmon:v1.5.0

## CSI PowerMax
########################
csi-powermax:
  enabled: false
  namespace: 
  global:
    storageArrays:
      - storageArrayId: "000000000001"
        endpoint: https://primary-1.unisphe.re:8443
        backupEndpoint: https://backup-1.unisphe.re:8443
  #    - storageArrayId: "000000000002"
  #      endpoint: https://primary-2.unisphe.re:8443
  #      backupEndpoint: https://backup-2.unisphe.re:8443
    managementServers:
      - endpoint: https://primary-1.unisphe.re:8443
      - endpoint: https://backup-1.unisphe.re:8443
  #    - endpoint: https://primary-2.unisphe.re:8443
  #    - endpoint: https://backup-2.unisphe.re:8443
  version: "v2.6.0"
  images:
    driverRepository: "dellemc"
  clusterPrefix: ABC
  portGroups: PortGroup1, PortGroup2, PortGroup3
  controller:
    controllerCount: 2
    snapshot:
      enabled: true
    resizer:
      enabled: true
    healthMonitor:
      enabled: false
    nodeSelector:
  node:
    healthMonitor:
      enabled: false
    nodeSelector:
  csireverseproxy:
    image: dellemc/csipowermax-reverseproxy:v2.5.0
    deployAsSidecar: true
    namespace: 
  replication:
    enabled: false
    image: dellemc/dell-csi-replicator:v1.4.0 
  migration:
    enabled: false
    image: dellemc/dell-csi-migrator:v1.1.0
    nodeRescanSidecarImage: dellemc/dell-csi-node-rescanner:v1.0.0
  authorization:
    enabled: false
    sidecarProxyImage: dellemc/csm-authorization-sidecar:v1.6.0
    proxyHost:
  vSphere:
    enabled: false
    fcPortGroup: "csi-vsphere-VC-PG"
    fcHostName: "csi-vsphere-VC-HN"
    vCenterHost: "00.000.000.00"
    vCenterCredSecret: vcenter-creds

## CSI PowerScale
########################
csi-isilon:
  enabled: false
  version: "v2.6.0"
  images:
    driverRepository: dellemc
  ## Controller ATTRIBUTES
  controller:
    controllerCount: 2
    healthMonitor:
      enabled: false
    nodeSelector:
    replication:
      enabled: false
      image: dellemc/dell-csi-replicator:v1.4.0
    vgsnapshot:
      enabled: false
      image: dellemc/csi-volumegroup-snapshotter:v1.2.0
    snapshot:
      enabled: true
    resizer:
      enabled: true
  ## Node ATTRIBUTES
  node:
    healthMonitor:
      enabled: false
    nodeSelector:
    # Uncomment if CSM for Resiliency and CSI Driver pods monitor are enabled
    # tolerations:
    #   - key: "offline.vxflexos.storage.dell.com"
    #     operator: "Exists"
    #     effect: "NoSchedule"
    #   - key: "vxflexos.podmon.storage.dell.com"
    #     operator: "Exists"
    #     effect: "NoSchedule"
    #   - key: "offline.unity.storage.dell.com"
    #     operator: "Exists"
    #     effect: "NoSchedule"
    #   - key: "unity.podmon.storage.dell.com"
    #     operator: "Exists"
    #     effect: "NoSchedule"
    #   - key: "offline.isilon.storage.dell.com"
    #     operator: "Exists"
    #     effect: "NoSchedule"
    #   - key: "isilon.podmon.storage.dell.com"
    #     operator: "Exists"
    #     effect: "NoSchedule"

  # Enable this feature only after contact support for additional information
  podmon:
    enabled: false
    image: dellemc/podmon:v1.5.0
  authorization:
    enabled: false
    sidecarProxyImage: dellemc/csm-authorization-sidecar:v1.6.0
    proxyHost:
  encryption:
    enabled: false

## CSI PowerFlex
########################
csi-vxflexos:
  enabled: false
  version: v2.6.0
  images:
    driverRepository: dellemc
    powerflexSdc: dellemc/sdc:3.6.0.6
  certSecretCount: 0
  controller:
    replication:
      enabled: false
      image: dellemc/dell-csi-replicator:v1.4.0
    healthMonitor:
      enabled: false
    controllerCount: 2
    snapshot:
      enabled: true
    resizer:
      enabled: true
    nodeSelector:
  node:
    healthMonitor:
      enabled: false
    nodeSelector:
    tolerations:
    # Uncomment if CSM for Resiliency and CSI Driver pods monitor is enabled 
    # - key: "offline.vxflexos.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # - key: "vxflexos.podmon.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # - key: "offline.unity.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # - key: "unity.podmon.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # - key: "offline.isilon.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # - key: "isilon.podmon.storage.dell.com"
    #   operator: "Exists"
    #   effect: "NoSchedule"
  monitor:
    enabled: false
  vgsnapshotter:
    enabled: false
    image: dellemc/csi-volumegroup-snapshotter:v1.2.0
  podmon:
    enabled: false
    image: dellemc/podmon:v1.5.0
  authorization:
    enabled: false
    sidecarProxyImage: dellemc/csm-authorization-sidecar:v1.6.0
    proxyHost:

## CSI Unity
########################
csi-unity:
  enabled: false
  version: "v2.6.0"

  # certSecretCount: Represents number of certificate secrets, which user is going to create for
  # ssl authentication. (unity-cert-0..unity-cert-n)
  # Allowed values: n, where n > 0
  certSecretCount: 1

  # fsGroupPolicy: Defines if the underlying volume supports changing ownership and permission of the volume before being mounted.
  # Allowed values:
  #   ReadWriteOnceWithFSType: supports volume ownership and permissions change only if the fsType is defined
  #   and the volume's accessModes contains ReadWriteOnce.
  #   File: kubernetes may use fsGroup to change permissions and ownership of the volume 
  #   to match user requested fsGroup in the pod's security policy regardless of fstype or access mode.
  #   None: volumes will be mounted with no modifications.
  # Default value: ReadWriteOnceWithFSType
  fsGroupPolicy: ReadWriteOnceWithFSType

  #To set nodeSelectors and tolerations for controller.
  # controller: configure controller pod specific parameters
  controller:
    controllerCount: 2

    snapshot:
      enabled: true

    resizer:
      enabled: true

    nodeSelector:

    healthMonitor:
      enabled: false

  # node: configure node pod specific parameters
  node:
    # dnsPolicy : Define the DNS Policy of the Node service.
    # ClusterFirstWithHostNet is the recommended and default DNS policy for the driver.
    # Prior to v1.6 of the driver, the default DNS policy was ClusterFirst.
    # In certain scenarios, users might need to change the default dnsPolicy.
    # Default value: None
    dnsPolicy: "ClusterFirstWithHostNet"

    healthMonitor:
      enabled: false

    nodeSelector:

    # tolerations: Define tolerations for the node daemonset, if required.
    # Default value: None
    tolerations:
    # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
    #  - key: "node-role.kubernetes.io/master"
    #    operator: "Exists"
    #    effect: "NoExecute"
    # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
    #  - key: "node-role.kubernetes.io/control-plane"
    #    operator: "Exists"
    #    effect: "NoExecute"
    #  - key: "node.kubernetes.io/memory-pressure"
    #    operator: "Exists"
    #    effect: "NoExecute"
    #  - key: "node.kubernetes.io/disk-pressure"
    #    operator: "Exists"
    #    effect: "NoExecute"
    #  - key: "node.kubernetes.io/network-unavailable"
    #    operator: "Exists"
    #    effect: "NoExecute"
    # Uncomment if CSM for Resiliency and CSI Driver pods monitor are enabled 
    #  - key: "offline.vxflexos.storage.dell.com"
    #    operator: "Exists"
    #    effect: "NoSchedule"
    #  - key: "vxflexos.podmon.storage.dell.com"
    #    operator: "Exists"
    #    effect: "NoSchedule"
    #  - key: "offline.unity.storage.dell.com"
    #    operator: "Exists"
    #    effect: "NoSchedule"
    #  - key: "unity.podmon.storage.dell.com"
    #    operator: "Exists"
    #    effect: "NoSchedule"
    #  - key: "offline.isilon.storage.dell.com"
    #    operator: "Exists"
    #    effect: "NoSchedule"
    #  - key: "isilon.podmon.storage.dell.com"
    #    operator: "Exists"
    #    effect: "NoSchedule"
  podmon:
    enabled: false
    image: dellemc/podmon:v1.5.0

  # allowRWOMultiPodAccess - Flag to enable sharing of volumes across multiple pods within the same node in RWO access mode.
  allowRWOMultiPodAccess: "false"

  # maxUnityVolumesPerNode - Maximum number of volumes that controller can publish to the node.
  maxUnityVolumesPerNode: 0

  # tenantName - Tenant name that need to added while adding host entry to the array.
  tenantName: ""

  images:
    driverRepository: dellemc

## K8S/Module ATTRIBUTES
##########################################

## Replication
########################
csm-replication:
  enabled: false
  namespace: 

## Observability
########################
karavi-observability:
  enabled: false
  namespace: 
  karaviMetricsPowerstore:
    enabled: false
  karaviMetricsPowerflex:
    enabled: false
  karaviMetricsPowerscale:
    enabled: false
  karaviMetricsPowermax:
    enabled: false
  cert-manager:
    enabled: false

## Application-Mobility 
########################
csm-application-mobility:
  enabled: false
  namespace:  
  # csm-application-mobility requires velero. If velero is already installed on the cluster, specify the namespace in which velero is deployed. Default value is "velero"
  veleroNamespace: velero
  # csm-application-mobility requires velero. If velero is not already present in cluster, set enabled to true to install it too.
  velero:
    enabled: true
    credentials:
      secretContents:
        cloud: |
          [default]
          aws_access_key_id=access_key
          aws_secret_access_key=secret_access_key
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: velero-bucket
        config: {}
          #region: 
          #s3ForcePathStyle: 
          #s3Url: 
          #publicUrl:
    initContainers:
    - name: dell-custom-velero-plugin
      image: dellemc/csm-application-mobility-velero-plugin:v0.3.0
      volumeMounts:
      - mountPath: /target
        name: plugins
    #- name: velero-plugin-for-aws
      #image: velero/velero-plugin-for-aws:v1.5.0
      #volumeMounts:
      #- mountPath: /target
        #name: plugins

## K8S/Cert-manager ATTRIBUTES
########################
cert-manager: 
  enabled: false
  namespace: 
  