{{- if eq .Values.openshift true }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: proxy-server
  namespace: {{ include "custom.namespace" . }}
  {{- if .Values.authorization.gateway.annotations }}
  annotations:
    {{- range $key, $value := .Values.authorization.gateway.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  host: {{ .Values.authorization.hostname }}
  port:
    targetPort: 8080
  tls:
    termination: edge
    {{- if and (.Values.authorization.certificate) (.Values.authorization.privateKey) }}
    certificate: |
      {{ .Values.authorization.certificate | nindent 6 }}
    key: |
      {{ .Values.authorization.privateKey | nindent 6 }}
    {{- end }}
  to:
    kind: Service
    name: proxy-server
    weight: 100
  wildcardPolicy: None
{{- else }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: proxy-server
  namespace: {{ include "custom.namespace" . }}
  {{- if .Values.authorization.gateway.annotations }}
  annotations:
    {{- range $key, $value := .Values.authorization.gateway.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.authorization.gateway.gatewayClassName }}
  listeners:
  - name: https
    protocol: HTTPS
    port: {{ .Values.authorization.gateway.port | default 443 }}
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        {{- if and (.Values.authorization.certificate) (.Values.authorization.privateKey) }}
        name: user-provided-tls
        {{- else }}
        name: karavi-selfsigned-tls
        {{- end }}
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: proxy-server
  namespace: {{ include "custom.namespace" . }}
spec:
  parentRefs:
  - name: proxy-server
    namespace: {{ include "custom.namespace" . }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: proxy-server
      port: 8080
{{- end }}
