apiVersion: v2
appVersion: "2.12.0"
name: csi-powerstore
version: 2.12.0
description: |
  PowerStore CSI (Container Storage Interface) driver Kubernetes
  integration. This chart includes everything required to provision via CSI as
  well as a PowerStore StorageClass.
type: application
kubeVersion: ">= 1.24.0"
# If you are using a complex K8s version like "v1.24.3-mirantis-1", use this kubeVersion check instead
# kubeVersion: ">= 1.23.0-0"
keywords:
  - csi
  - storage
home: https://github.com/dell/csi-powerstore
sources:
  - https://github.com/dell/csi-powerstore
maintainers:
  - name: DellEMC
