apiVersion: v2
appVersion: 2.9.0
name: csi-unity
version: 2.9.0
description: |
  Unity XT CSI (Container Storage Interface) driver Kubernetes
  integration. This chart includes everything required to provision via CSI as
  well as a Unity XT StorageClass.
type: application
kubeVersion: ">= 1.24.0 < 1.29.0"
# If you are using a complex K8s version like "v1.24.3-mirantis-1", use this kubeVersion check instead
# WARNING: this version of the check will allow the use of alpha and beta versions, which is NOT SUPPORTED
# kubeVersion: ">= 1.24.0-0 < 1.29.0-0"
keywords:
- csi
- storage
sources:
- https://github.com/dell/csi-unity
maintainers:
- name: DellEMC