{{ if .Values.karaviMetricsPowermax.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-metrics-powermax-controller
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-metrics-powermax-controller
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes", "storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "nodes"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "watch", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-metrics-powermax-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-metrics-powermax-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-metrics-powermax-controller
  apiGroup: rbac.authorization.k8s.io

{{ end }}

