{{- if eq .Values.redis.useSecretProviderClass false }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-csm-secret
  namespace: {{ include "custom.namespace" . }}
type: kubernetes.io/basic-auth
stringData:
  password: K@ravi123!
  commander_user: dev
{{- end }}
