apiVersion: v2
name: csi-isilon
version: 2.16.0
appVersion: "2.16.0"
kubeVersion: ">= 1.24.0"
# If you are using a complex K8s version like "v1.24.0-mirantis-1", use this kubeVersion check instead
# kubeVersion: ">= 1.24.0-0"
description: |
  PowerScale CSI (Container Storage Interface) driver Kubernetes
  integration. This chart includes everything required to provision via CSI as
  well as an Isilon StorageClass.
type: application
keywords:
  - csi
  - storage
maintainers:
  - name: DellEMC
sources:
  - https://github.com/dell/csi-isilon
