apiVersion: v2
name: csi-isilon
version: 2.9.0
appVersion: "2.9.0"
kubeVersion: ">= 1.21.0 < 1.29.0"
#If you are using a complex K8s version like "v1.22.3-mirantis-1", use this kubeVersion check instead
#WARNING: this version of the check will allow the use of alpha and beta versions, which is NOT SUPPORTED
#kubeVersion: ">= 1.21.0-0 < 1.29.0-0"
description: |
  PowerScale CSI (Container Storage Interface) driver Kubernetes
  integration. This chart includes everything required to provision via CSI as
  well as an Isilon StorageClass.
type: application
keywords:
- csi
- storage
maintainers:
- name: DellEMC
sources:
- https://github.com/dell/csi-isilon
